### ISSUE TITLE
Escolher um framework em Python

### ISSUE THREAD

**Issue by annecarv** [annecarv/tetris_py#1]

**Comment by annecarv** [comment]
O Django fornece aos seus programadores e programadoras uma construção de sites rápida e com o uso de pouco código.

De modo geral, um projeto desenvolvido com o Django costuma ser dividido em pequenas aplicações compostas por um pacote Python que, por sua vez, resolve porções específicas de requisições relativas àquela aplicação.

Cada uma destas pequenas aplicações baseia-se no modelo MVT -- ou Model-View-Template, os três aspectos de uma aplicação web trabalhados pelo Django.

Mais detalhadamente, são eles:

Model: o modelo é a estrutura que representa os dados dessa aplicação, ou seja, possui ligação direta com um banco de dados. Esta é a camada de abstração feita para manipular, incluir ou excluir dados. Sempre que um model é criado, o Django fornece uma API para esta manipulação.
View: o view é uma função Python feita para receber uma requisição e enviar uma resposta em retorno. É aqui onde os dados são extraídos e produzem uma resposta.
Template: esta é a camada onde o template da aplicação é produzido através de artefatos compreendidos pelo navegador web. Esta é a parte que diz respeito a tudo que o usuário final é capaz de visualizar em seu dispositivo.

https://kenzie.com.br/blog/django/

**Comment by isacmoura** [comment]
MVT: https://www.treinaweb.com.br/blog/entendendo-o-mtv-do-django

**Comment by isacmoura** [comment]
Acredito que a issue pode ser fechada. Django será o framework usado no projeto.
